# Generated by Django 5.0.1 on 2025-01-14 00:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ApprovalList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
            ],
            options={
                "verbose_name_plural": "Approval_List",
            },
        ),
        migrations.CreateModel(
            name="Area",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name_plural": "Areas",
            },
        ),
        migrations.CreateModel(
            name="Assignee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
            ],
            options={
                "verbose_name_plural": "Assignees",
            },
        ),
        migrations.CreateModel(
            name="ItemStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
            ],
            options={
                "verbose_name_plural": "Item_Status",
            },
        ),
        migrations.CreateModel(
            name="Manufacturer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name_plural": "Manufacturers",
            },
        ),
        migrations.CreateModel(
            name="MapLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name_plural": "Map_Locations",
            },
        ),
        migrations.CreateModel(
            name="InventoryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("asset_id", models.CharField(blank=True, max_length=100)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("model_no", models.CharField(max_length=100)),
                ("serial_no", models.CharField(blank=True, max_length=100, null=True)),
                ("qty", models.IntegerField()),
                (
                    "total_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "cost_per_item",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("approved_date", models.DateField()),
                ("purchased_from", models.CharField(blank=True, max_length=100)),
                ("purchase_date", models.DateField()),
                ("inserted_by", models.CharField(blank=True, null=True)),
                ("inserted_date", models.DateField()),
                (
                    "modified_by",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("modified_date", models.DateField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.approvallist",
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.assignee",
                    ),
                ),
                (
                    "item_area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="inventory.area"
                    ),
                ),
                (
                    "stat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.itemstatus",
                    ),
                ),
                (
                    "mfg",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.manufacturer",
                    ),
                ),
                (
                    "item_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.maplocation",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Inventory_Items",
            },
        ),
        migrations.CreateModel(
            name="ItemNotes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.TextField()),
                ("inserted_by", models.CharField(max_length=250)),
                (
                    "inserted_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.inventoryitem",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Item_Notes",
            },
        ),
        migrations.AddField(
            model_name="area",
            name="map_loc",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="inventory.maplocation"
            ),
        ),
    ]
