# Generated by Django 3.2.7 on 2021-10-06 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automotive', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dealership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=4)),
                ('_state', models.CharField(max_length=17)),
                ('postal_code', models.CharField(max_length=8)),
                ('office_number', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Advisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=50)),
                ('employee_number', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=50)),
                ('contact_number', models.CharField(max_length=15)),
                ('dealership', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='automotive.dealership')),
            ],
        ),
    ]
