# Generated by Django 3.2.7 on 2021-10-06 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automotive', '0004_auto_20211006_0044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dealership',
            old_name='_state',
            new_name='dealership_state',
        ),
    ]
