# Generated by Django 3.2.7 on 2021-10-07 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automotive', '0005_rename__state_dealership_dealership_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='link',
            field=models.TextField(blank=True),
        ),
    ]
