# Generated by Django 3.2.7 on 2021-10-07 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automotive', '0006_alter_service_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='service',
            name='inserted_date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='mileage',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_date',
            field=models.DateField(blank=True),
        ),
    ]
