# Generated by Django 3.2.7 on 2021-10-07 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automotive', '0007_auto_20211006_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8),
        ),
    ]
