# Generated by Django 3.2.7 on 2021-10-07 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automotive', '0008_alter_service_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisor',
            name='email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='advisor',
            name='first_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='dealership',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
