# Generated by Django 3.2.8 on 2021-10-28 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('vendor_state', models.CharField(max_length=2)),
                ('postal_code', models.CharField(max_length=8)),
                ('office_number', models.CharField(max_length=15)),
                ('website', models.TextField()),
            ],
        ),
    ]
