# Generated by Django 3.2.8 on 2021-10-28 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('residential', '0002_auto_20211028_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='email',
            field=models.EmailField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_date', models.DateField()),
                ('name', models.CharField(max_length=60)),
                ('vendor_rep', models.CharField(blank=True, max_length=50)),
                ('contact_num', models.CharField(blank=True, max_length=10)),
                ('documentation', models.TextField()),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=8)),
                ('notes', models.TextField(blank=True)),
                ('vendor', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='residential.vendor')),
            ],
        ),
    ]
