# Generated by Django 3.2.8 on 2021-10-28 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residential', '0003_auto_20211028_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='documentation',
            field=models.TextField(blank=True),
        ),
    ]
