# Generated by Django 5.0.1 on 2024-08-09 12:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExpenseType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("expense_date", models.DateField()),
                ("name", models.CharField(max_length=200)),
                ("org", models.CharField(max_length=200)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=7)),
                ("notes", models.CharField(blank=True, max_length=200)),
                (
                    "inserted_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "expense_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="expense_tracking.expensetype",
                    ),
                ),
            ],
        ),
    ]
