# Generated by Django 5.0.1 on 2024-08-18 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expense_tracking", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Budget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("beginning_bal", models.DecimalField(decimal_places=2, max_digits=7)),
                (
                    "budget_amt",
                    models.DecimalField(decimal_places=2, max_digits=7, null=True),
                ),
                (
                    "total_monthly_bal",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=7, null=True
                    ),
                ),
                (
                    "expense_amt",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=7, null=True
                    ),
                ),
                (
                    "current_bal",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=7, null=True
                    ),
                ),
            ],
        ),
    ]
